### ISSUE TITLE
ModuleNotFoundError: No module named 'zyre'

### ISSUE THREAD

**Issue by amruk20** [Hemisphere-Project/HPlayer2#10]
Hi There

Running on a RPI3 and Raspbian 

I have managed to get through individually installing a number of the modules that have thrown up as missing but have got to "zyre" and not sure what module this is based around as simply doing a pip install of it claims to not find it.

Any help much appreciated!

**Comment by Maigre** [comment]
Hi, sorry for the late reply, 
to install Zyre, refer to https://github.com/Hemisphere-Project/HPlayer2/blob/master/scripts/install_dependencies.sh
The last part downloads, compiles and install Zyre.
Best,
Thomas
