### ISSUE TITLE
Install script exits at line 43

### ISSUE THREAD

**Issue by GuntherSe** [Hemisphere-Project/HPlayer2#4]
Very cool project!!!

(scripts/build_debian.sh)
...
cd "$(dirname "$0")"
./select_prebuild
if [ $? -eq 0 ]
then
	echo ""
  echo "Building MPV for your system..."
else
  exit
fi
**--------------------------------------->>> Script exits here**
so I manually executed the following lines in a terminal.
...
# RPi MMAL
if [[ $(uname -m) = armv* ]]; then
	echo --enable-mmal > ffmpeg_options
fi

# Build
./rebuild -j4
**--------------------------------------->>> my PI3 stopped due to overheating. Without the -j4 option it worked**
cd ..

# Copy bin
mkdir -p bin
cp mpv-build/mpv/build/mpv  bin/mpv

# Clean
rm -fR mpv-build

**Comment by Maigre** [comment]
README updated with more detailed and up-to-date documentation !

The updated build script is now **scripts/build.sh**
and supports both **arch** and **xbian** (raspbian/debian/ubuntu)
